export const FEDERAL_COURTS = [
  { id: "scotus", name: "Supreme Court of the United States" },
  // Circuit Courts
  { id: "ca1", name: "First Circuit" },
  { id: "ca2", name: "Second Circuit" },
  { id: "ca3", name: "Third Circuit" },
  { id: "ca4", name: "Fourth Circuit" },
  { id: "ca5", name: "Fifth Circuit" },
  { id: "ca6", name: "Sixth Circuit" },
  { id: "ca7", name: "Seventh Circuit" },
  { id: "ca8", name: "Eighth Circuit" },
  { id: "ca9", name: "Ninth Circuit" },
  { id: "ca10", name: "Tenth Circuit" },
  { id: "ca11", name: "Eleventh Circuit" },
  { id: "cadc", name: "D.C. Circuit" },
  { id: "cafc", name: "Federal Circuit" },
  // District Courts - Major
  { id: "nysd", name: "Southern District of New York" },
  { id: "nyed", name: "Eastern District of New York" },
  { id: "nynd", name: "Northern District of New York" },
  { id: "nywd", name: "Western District of New York" },
  { id: "cacd", name: "Central District of California" },
  { id: "cand", name: "Northern District of California" },
  { id: "casd", name: "Southern District of California" },
  { id: "caed", name: "Eastern District of California" },
  { id: "ilnd", name: "Northern District of Illinois" },
  { id: "txsd", name: "Southern District of Texas" },
  { id: "txnd", name: "Northern District of Texas" },
  { id: "txed", name: "Eastern District of Texas" },
  { id: "txwd", name: "Western District of Texas" },
  { id: "flsd", name: "Southern District of Florida" },
  { id: "flmd", name: "Middle District of Florida" },
  { id: "flnd", name: "Northern District of Florida" },
  { id: "paed", name: "Eastern District of Pennsylvania" },
  { id: "pawd", name: "Western District of Pennsylvania" },
  { id: "mad", name: "District of Massachusetts" },
  { id: "dcd", name: "District of Columbia" },
  { id: "njd", name: "District of New Jersey" },
  { id: "gand", name: "Northern District of Georgia" },
  { id: "vaed", name: "Eastern District of Virginia" },
  { id: "vawd", name: "Western District of Virginia" },
  { id: "mdd", name: "District of Maryland" },
  { id: "ded", name: "District of Delaware" },
  { id: "ctd", name: "District of Connecticut" },
  { id: "cod", name: "District of Colorado" },
  { id: "azd", name: "District of Arizona" },
  { id: "wad", name: "Western District of Washington" },
  { id: "waed", name: "Eastern District of Washington" },
  { id: "ohnd", name: "Northern District of Ohio" },
  { id: "ohsd", name: "Southern District of Ohio" },
  { id: "mied", name: "Eastern District of Michigan" },
  { id: "miwd", name: "Western District of Michigan" },
  { id: "mnd", name: "District of Minnesota" },
  { id: "mowd", name: "Western District of Missouri" },
  { id: "moed", name: "Eastern District of Missouri" },
  { id: "ncd", name: "Western District of North Carolina" },
  { id: "ncmd", name: "Middle District of North Carolina" },
  { id: "nced", name: "Eastern District of North Carolina" },
  { id: "laed", name: "Eastern District of Louisiana" },
  { id: "lawd", name: "Western District of Louisiana" },
] as const;

export type CourtId = (typeof FEDERAL_COURTS)[number]["id"];
